version: '3'

services:
 database:
    image: bitnami/postgresql
    ports: 
      - '5433:5432'
    container_name: project-management-plan
    restart: always
    volumes: 
      - project-management-plan-disk:/var/lib/postgresql/data
    environment: 
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: projectManagementPlan
volumes: 
  Search-healthy-disk: